# Generated by Django 4.1.3 on 2024-09-17 21:00

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default=1, upload_to=places.models.custom_upload_to, verbose_name='Foto del lugar'),
            preserve_default=False,
        ),
    ]
