# Generated by Django 4.1.3 on 2024-09-18 20:36

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to=article.models.custom_upload_to, verbose_name='Imagen del artículo'),
            preserve_default=False,
        ),
    ]
